services:
  - type: web
    name: vectorstore-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PERSIST_DIRECTORY
        value: /data/vectorstore

databases:
  - name: vectorstore
    databaseName: vectorstore
    user: vectorstore