services:
  - type: web
    name: vectorstore-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --timeout 500 --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: PERSIST_DIRECTORY
        value: /data/vectorstore

databases:
  - name: vectorstore
    databaseName: vectorstore
    user: vectorstore